let GAME_LEVELS = [
    ["                                                                                ",
        "                                                                                ",
        "                                                                                ",
        "                                                                                ",
        "                                                                                ",
        "                                                                                ",
        "                                                                  xxx           ",
        "                                                   xx      xx    xx!xx          ",
        "                                    o o      xx                  x!!!x          ",
        "                                   %                             xx!xx          ",
        "                                   xxxxx                          xvx           ",
        "                                                                            xx  ",
        "  xx                                      o o                                x  ",
        "  x                     o                                                    x  ",
        "  x                                      xxxxx                             o x  ",
        "  x  @       xxxx       o                                                    x  ",
        "  x          xxxx%        %                                      xxxxx       x  ",
        "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx  ",
        "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx  ",
        "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx    !xxxxxxxxxxxxxxxxxxx  ",
        "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxx  ",
        "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  "],


       ["                                      x!!x                         xxxxxxx                                    x!x  ",
        "                                      x!!x                      xxxx     xxxx                                 x!x  ",
        "                                      x!!xxxxxxxxxx            xx           xx                                x!x  ",
        "                                      xx!!!!!!!!!!xx          xx             xx                               x!x  ",
        "                                       xxxxxxxxxx!!x          x                                    o   o   o  x!x  ",
        "                                                xx!x          x     o   o                      %             xx!x  ",
        "                                                 x!x          x                                xxxxxxxxxxxxxxx!!x  ",
        "                                                 xvx          x     x   x                        !!!!!!!!!!!!!!xx  ",
        "                                                              xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
        "                                                               xx!!!!!!!!!!!xx            v                        ",
        "                                                                xxxx!!!!!xxxx                                      ",
        "                                               x      x            xxxxxxx        xxx         xxx!!!!!!!!!!!!!!!!!!",
        "                                               xx     x                           x x         x!x!!!!!!!!!!!!!!!!!!",
        "                                               x      x                             x         x!!!!!!!!!!!!!!!!!!!!",
        "                                               x      x                             xx        x!!!!!!!!!!!!!!!!!!!!",
        "                                               x     xx                             x         x!!!!!!!!!!!!!!!!!!!!",
        "               %                               x      x      o  o     x   x         x         x!!!!!!!!!!!!!!!!!!!!",
        "               xxxxxxx        xxx   xxx        x      x               x   x         x         x!!!!!!!!!!!!!!!!!!!!",
        "              xxxxxxxxx         x   x          xx     x     xxxxxx    x   x   xxxxxxxxx       x!!!!!!!!!!!!!!!!!!!!",
        "     @       xxxxxxxxxxx        x o x          x      x!!!!!!!!!!!!!!!x   x   x               x!!!!!!!!!!!!!!!!!!!!",
        "             xxxxxxxxxxx        x   x          x      x!!!!!!!!!!!!!!!x   x   x               x!!!!!!!!!!!!!!!!!!!!",
        "             xxxxxxxxxxx        x   x          x     xx!!!!!!!!!!!!!!!x   x   x               x!!!!!!!!!!!!!!!!!!!!",
        "    xxx      xxxxxxxxxxx        x   x          x      x!!!!!!!!!!!!!!!x   xxxxx     xxxx      x!!!!!!!!!!!!!!!!!!!!",
        "    xxx      xxxxxxxxxxx       xx o xx         x      x!!!!!!!!!!!!!!!x     o       x         x!!!!!!!!!!!!!!!!!!!!",
        "    xxx      xxxxxxxxxxx       xx o xx         x      x!!!!!!!!!!!!!!!x             x         x!!!!!!!!!!!!!!!!!!!!",
        "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!xx     xx!!!!!!!!xx     x!!!!!!!!!!!!!!!x     =       x         x!!!!!!!!!!!!!!!!!!!!",
        "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!xx       xxxxxxxxxx      x!!!!!!!xx!!!!!!xxxxxxxxxxxxxxxx  o o  xx!!!!!!!!!!!!!!!!!!!!",
        "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!x    o                  xx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!xx     xx!!!!!!!!!!!!!!!!!!!!!",
        "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!x                       xx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!xx     xx!!!!!!!!!!!!!!!!!!!!!",
        "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!x                      xx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!",
        "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!xx       xxxxxxxxxxxxxxx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
        "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
        "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
       ["                                                                                                              ",
        "                                                                                                              ",
        "                                                                                                              ",
        "                                                                                                              ",
        "                                                                                                              ",
        "                                        o                                                                     ",
        "                                                                                                              ",
        "                                        x                                                                     ",
        "                                        x                                                                     ",
        "                                        x                                                                     ",
        "                                        x                                                                     ",
        "                                       xxx                                                                    ",
        "                                       x x                 !!!        !!!  xxx                                ",
        "                                       x x                 !x!        !x!                                     ",
        "                                     xxx xxx                x          x                                      ",
        "                                      x   x                 x   oooo   x         xxx                          ",
        "                                      x   x                 x          x        x!!!x                         ",
        "                                      x   x                 xxxxxxxxxxxx         xxx                          ",
        "                                     xx   xx     x    x      x                                                ",
        "                                      x   xxxxxxxx    xxxxxxxx              x x                               ",
        "                                      x   x           x                    x!!!x                              ",
        "                                      x   x           x                     xxx                               ",
        "                                     xx   xx          x                                                       ",
        "                                      x   x= = = =    x            xxx                                        ",
        "                                      x   x           x           x!!!x                                       ",
        "                                      x   x    = = = =x     o      xxx       xxx                              ",
        "                                     xx   xx          x                     x!!!x                             ",
        "                              o   o   x   x           x     x                xxv        xxx                   ",
        "                                      x   x           x              x                 x!!!x                  ",
        "                             xxx       x xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
        "                             x xxx     xxx x          x!!!!!!!!!!!!!!x                                        ",
        "                             x             x     xxxxxxxxxxxxxxxxxxxxx                                        ",
        "                             xx           xx                                         xxx                      ",
        "  xxx                         x           x                                         x!!!x                xxx  ",
        "  x x                         x    xxx    x    %                                     xxx                 x x  ",
        "  x                           x    xxx    xxxxxx                         xxxxx                             x  ",
        "  x                           x           x                              x   x                             x  ",
        "  x                           xx         xx                              x x x                             x  ",
        "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
        "  x                xxx             o o    x                              x         xxx                     x  ",
        "  x               xxxxx            xxx    x                             xxx       x!!!x          x         x  ",
        "  x               oxxxo       xx   xxx    x                             x x        xxx          xxx        x  ",
        "  x   @            xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
        "  x                 x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
        "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
        "                                                                                                              ",
        "                                                                                                              "],
       ["                                                                                                  xxx x       ",
        "                                                                                                      x       ",
        "                                                                                                  xxxxx       ",
        "                                                                                                  x           ",
        "                                                                                                  x xxx       ",
        "                          o                                                                       x x x       ",
        "                                                                                             o o oxxx x       ",
        "                   xxx                                        %                                       x       ",
        "       !   o   !                                              xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
        "       x       x                                              x   x x   x x   x x   x x   x x   x x           ",
        "       x=  o   x          x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
        "       x       x                                                x x   x x   x x   x x   x x   x x     x       ",
        "       !   o   !          o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
        "                                                                                                              ",
        "          o              xxx                              xx                                                  ",
        "                                                                                                              ",
        "                                                                                                              ",
        "                                                    xx                                                        ",
        "                   xxx         xxx                                                                            ",
        "                                                                                                              ",
        "                          o                                                     x      x                      ",
        "                                                          xx     xx                                           ",
        "             xxx         xxx         xxx                                 x                  x                 ",
        "                                                                                                              ",
        "                                                                 ||                                           ",
        "  xxxxxxxxxx     %                                                                                            ",
        "  x        x  o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
        "  x @      x    x       x   x       x   x                 ||                  x     x                         ",
        "  x        xxxxxx   o   xxxxx   o   xxxxx                                                                     ",
        "  xxxxx                                       xxxxx       xx     xx     xxx                                   ",
        "      x                                       xxxxx                     xxx                                   ",
        "      x=                    =                =xxxxx                     xxx                                   ",
        "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
    module.exports = GAME_LEVELS;
